version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - '3001:3001'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    depends_on:
      - db

volumes:
  postgres-data:
